name: PyPI Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # Match tags like v0.1.0, v1.2.3, v1.2.3-alpha.1
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing
      contents: write # Required for creating releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv with python 3.11
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
          python-version: 3.11

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Generate changelog and create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: false
          files: dist/*
